spring:
   profiles: eureka3
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:8770/eureka/
#
#spring:
#  application:
#    name: eurka-server

